MoneyManager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:id>', views.delete, name='delete'),
]

hal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('MoneyManager/', include('MoneyManager.urls')),
    path('login/', include('login.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

login/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.login_user, name="login_user"),
    path('register/', views.register_user, name="register_user"),
    path('home/', views.home, name="home"),
    path('logout_user', views.logout_user, name="logout_user"),
]

MoneyManager/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class movimenti(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    data = models.DateField()
    nome_icona = models.CharField(max_length=255)
    tipologia = models.CharField(max_length=2)
    cifra = models.FloatField()
    descrizione = models.CharField(max_length=255)



    def __unicode__(self):
        return self.user_id.id

login/models.py
from django.db import models

# Create your models here.

MoneyManager/forms.py
from django import forms
from .models import movimenti
from django.contrib.auth import authenticate, login
from django.forms import CheckboxInput, ModelChoiceField, Select, ModelMultipleChoiceField, SelectMultiple
from django.forms.widgets import DateInput, RadioSelect, Select


class MovimentiForm(forms.ModelForm):
    class Meta:
        TYPE = [('+', '+'), ('-', '-')]
        TYPE_DESCRIZIONE = [
            ('  ', '  .... '),
            ('Colazione', 'Colazione'),
            ('Pranzo', 'Pranzo'),
            ('Cena', 'Cena'),
            ('Spesa', 'Spesa'),
            ('Biglietto Treno', 'Biglietto Treno'),
            ('Biglietto Aereo', 'Biglietto Aereo'),
            ('Spesa', ' Spesa'),
            ('Cinema', 'Cinema'),
            ('Altro', 'Altro...'),
        ]
        user_id =  ['user']
        data = forms.DateField()
        descrizione = forms.CharField(max_length=20)
        tipologia = forms.ChoiceField(widget=forms.RadioSelect, choices=TYPE)
        cifra = forms.FloatField()

        model = movimenti
        fields = ['data', 'descrizione', 'tipologia', 'cifra', 'nome_icona']

        widgets = {
            'data' : DateInput(attrs={'type':'date'}),
            #'descrizione' : forms.Select(choices=TYPE_DESCRIZIONE, attrs={'class':'form-select'}),
            'tipologia' : forms.RadioSelect(choices=TYPE, attrs={'type':'radio'}),
        }

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=70)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name' ,'email', 'password1', 'password2')

MoneyManager/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .models import movimenti
from django.shortcuts import render, redirect
from .forms import MovimentiForm
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

#datetime per stampare l'anno corrente
x = datetime.datetime.now()
y = x.strftime("%Y")
def index(request):
    if  request.user.is_authenticated:
        list_mov = movimenti.objects.filter(user_id=request.user.id).order_by('-data').values()
        list_month = movimenti.objects.dates('data', 'month').filter(user_id=request.user.id)
        tot = calcola_totale(list_mov)
        form = MovimentiForm()

        if request.method == 'POST':
            form = MovimentiForm(request.POST)
            print(form.errors)
            if form.is_valid():
                form_list = form.save(commit=False)
                form_list.user_id = request.user
                form_list.save()
                return HttpResponseRedirect(reverse('index'))
            else:
                form = MovimentiForm()


        return render(request, 'moneymanager.html', {'list_mov':list_mov, 'form':form, 'tot':tot, 'list_month':list_month})
    else:
        return redirect('login_user')


def add_movimenti(request):
    if request.method == 'POST':
        form = MovimentiForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form_list = form.save(commit=False)
            form_list.user_id = request.user
            form_list.save()
            return HttpResponseRedirect('index')




def calcola_totale(list_mov):
    totale = 0

    for x in list_mov:
        if x.get("tipologia") == "+":
            str_conc = x.get("tipologia") + str(x.get("cifra"))
            num = float(str_conc)
            totale = round(totale +  num, 2)
        elif x.get("tipologia") == "-":
            str_conc = x.get("tipologia") + str(x.get("cifra"))
            num = float(str_conc)
            totale = round(totale +  num, 2)

    return totale

def delete(request, id):
  mov = movimenti.objects.get(id=id)
  mov.delete()
  return HttpResponseRedirect(reverse('index'))

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'home.html', {}) #reinderizzamento pagina contenete le app
        else:
            messages.success(request, ("C'è stato un errore durante l'autenticazione, riprova"))
            return render(request, 'login.html', {})
    else:
        return render(request, 'login.html', {})


def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registrazione avvenuta con successo"))
            return render(request, 'home.html', {}) #reinderizzamento pagina contenete le app
    else:
        form = RegisterUserForm()

    return render(request, 'register.html', {
        'form':form,
    })

def home(request):
    if  request.user.is_authenticated:
        return render(request, 'home.html', {})
    else:
        return redirect('login_user')

def logout_user(request):
    logout(request)
    messages.success(request, ("Log out effettuato"))
    return redirect('login_user')

MoneyManager/templates/moneymanager.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<title> Money Manager </title>
<link rel="stylesheet" href="{% static 'styles.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

  {% if user.is_authenticated %}
  <!--- LA SEZIONE DELLA NAV BAR ---->
  {% include 'nav_bar.html' %}


  <!--- SEZIONE DEI BOTTONI PER AGGIUNGERE UNA TRANSAZIONE IN POSITIVO O NEGATIVO --->
  <div class="container" role="main">
      <div  class="center-block text-center m-3">
        <button type="button" class="btn btn-danger btn-lg " style="margin:3%" id="rmButton">  Nuova Spesa  </button>
        <button type="button" class="btn btn-success btn-lg" style="margin:3%" id="addButton" >Nuova Entrata</button>
    </div>
  </div>

  <!--- CARD TOTALE DELLE ENTRATE E DELLE USCITE  --->
  <div class="card" style="margin-bottom:3%">
  <h6 class="card-header">Saldo Totale</h6>
  <div class="card-body">
    <h1 class="card-title">{{tot}} EUR </h1>
  </div>
</div>

  <!--- SEZIONE DELLE CARD PER VISUALIZZARE TUTTE LE TRANSAZIONI --->
{% for y in list_month%}
  <div class="card" style="" >
    <div  class = "card-header">
          <script>
            var m = ["","Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settemnbre", "Ottonbre", "Novembre", "Dicembre"];
            document.write(m["{{y.month}}"]);
           </script>

          {{ y.year }}
    </div>
    {%for x in list_mov %}
      {% if x.data.month == y.month %}
    <ul class="list-group list-group horizontal list-group-flash">
        <li class="list-group-item">
          <div class="container">
          <div class="row align-items-start ">
           <div class="col">
              <!--- Qua verrà fatto l'output di un'icona --->
              <i class="{{x.nome_icona}}" aria-hidden="true"></i>
           </div>
           <div class="col">
             <!--- Qua verrà fatto l'output della descrzione e della data--->
              <h5 class="card-title"> {{x.descrizione}} </h5>
              <p class="card-text"><small class="text-muted">{{x.data}}</small></p>
           </div>
           <div class="col">
             {% if x.tipologia == '-' %}
               <h5 style="color:red"> {{x.tipologia}} {{x.cifra}}</h5>
             {% else %}
               <h5 style="color:green"> {{x.tipologia}} {{x.cifra}}</h5>
                {%endif%}
           </div>
           <div class="col ">
             <a href="delete/{{ x.id }}">
               <i class="fa fa-trash fa-2x" style="color: #a3c2c2"></i>
             </a>

           </div>

        </div>
      </div>
        </li>
    </ul>
    {% endif %}
    {% endfor %}
  </div>
{% endfor%}



<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2 id="modal_head"></h2>
    </div>
<div class="modal-body">
  <form action="" method="POST">
   {% csrf_token %}
   <label for="{{ form.data.id_for_label }}">Inserisci data:</label>
   {{form.data}}

   <div class="form-box">
		<div class="button-box">
			<div id="btn"></div>
			<button type="button" class="toggle-btn" onclick="leftClick()">+</button>
			<button type="button" class="toggle-btn" onclick="rightClick()">-</button>
		</div>
	</div>

   {{form.tipologia.as_hidden}}
    <label for="{{ form.cifra.id_for_label }}">Inserisci cifra:</label>
   {{form.cifra}}
   <label for="{{ form.descrzione.id_for_label }}">Scegli descrizione:</label>
   {{form.descrizione}}
   {{form.nome_icona.as_hidden}}


   <button id="coll-btn" class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Scegli categoria ...
  </button>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
    <ul class="list-group">
      <!-- NOTA BENE GLI ELEMENTI DEVONO ESSERE AGGIUNTI NEL MEDESIMO MODO DI QUELLI ELENCATI SOTTO -->
      <li class="list-group-item"><i class="fa fa-shopping-basket fa-2x" aria-hidden="true"></i>  Spesa </li>
      <li class="list-group-item"><i class="fa fa-glass fa-2x" aria-hidden="true"></i> Bar</li>
      <li class="list-group-item"><i class="fa fa-cutlery fa-2x" aria-hidden="true"></i> Pranzo/Cena </li>
      <li class="list-group-item"><i class="fa fa-gift fa-2x" aria-hidden="true"></i> Regalo  </li>
      <li class="list-group-item"><i class="fa fa-film fa-2x" aria-hidden="true"></i> Cinema</li>
      <li class="list-group-item"><i class="fa fa-credit-card fa-2x" aria-hidden="true"></i>Carta di Credito</li>

      <li class="list-group-item"><i class="fa fa-train fa-2x" aria-hidden="tru</li>e"></i> Treno </li>
      <li class="list-group-item"><i class="fa fa-plane fa-2x" aria-hidden="tru</li>e"></i> Aereo </li>
      <li class="list-group-item"><i class="fa fa-car fa-2x" aria-hidden="tru</li>e"></i> Macchina </li>
      <li class="list-group-item"><i class="fa fa-bus fa-2x" aria-hidden="tru</li>e"></i> Bus </li>

      <li class="list-group-item"><i class="fa fa-envelope fa-2x" aria-hidden="true"></i> Stipendio</li>
      <li class="list-group-item"><i class="fa fa-usd fa-2x" aria-hidden="true"></i>Varie</li>
    </ul>
    </div>
  </div>

    <a href="thanks">
    <input type="submit" value="Salva" >
  </a>
  </form>

  </div>
</div>
</div>

  {% else %}
        <h1> Errore, devi effettuare il login..  </h1>
  {% endif %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("rmButton");

var btn_add = document.getElementById("addButton");
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
  rightClick();
}

btn_add.onclick = function() {
  modal.style.display = "block";
  leftClick();
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

$(document).ready(function(){
  // Controlla le icone
  $("li").each(function() {
    $(this).click(function(){
          $("#coll-btn").text("Scegli categoria...");
          $("#id_descrizione").val($(this).text());
          var string = $(this).html();
          string = string.split('</i>')[0];
          $("#coll-btn").append(string);
          string = string.substr(10);
          string = string.split('"')[0];
          $("#id_nome_icona").val(string);
          $("#coll-btn").click();

    })
  });
});

//Controlla il toggle switch button id_tipologia_0 = + mentre id_tipologia_1 = -
var button_toggle = document.getElementById('btn');
var modal_head = document.getElementById('modal_head');
var tipologia = document.getElementById('id_tipologia');

function leftClick() {
   button_toggle.style.left = '0'
   button_toggle.style.backgroundColor = "#4CAF50";
   modal_head.innerHTML = "Aggiungi nuova entrata";
   modal_head.style.color = "#4CAF50";
   tipologia.value = '+';
 }

 function rightClick() {
    button_toggle.style.left = '110px'
    button_toggle.style.backgroundColor = " #ff0000";
    modal_head.innerHTML = "Aggiungi nuova spesa";
    modal_head.style.color = "#ff0000";
    tipologia.value = '-';
  }


</script>

</body>
</html>

MoneyManager/templates/thanks.html
<h1> Movimento aggiunto con successo! </h1>

login/templates/home.html
<!DOCTYPE html>
<html>
<head>

{% load static %}
<title>HAL Home</title>
<link rel="stylesheet" href="{% static '/styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.cards {
  margin-left: 16px;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 20%;
}

.cards:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.container {
  text-align: center;
  margin-top: 16px;
  padding: 2px 16px;
}
</style>


</head>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1">
  {% if user.is_authenticated %}

    <!--- LA SEZIONE DELLA NAV BAR ---->
    {% include 'nav_bar.html' %}


        <!--- Qua vengono visualizzate tutte le app disponibili   --->
        <div class="cards">
          <div class="container">
            <a href="{%url 'index'%}">
            <i class="fa fa-money fa-5x" aria-hidden="true"></i> <br/>
          </a>
          <h3> Money Manager app </h3>
          <span>Ti permette di gestire le tue entrate e uscite e i tuoi risparmi </span>
          </div>
        </div>




    {% else %}
        <h1> Errore, devi effettuare il login.. </a> </h1>
     {% endif %}
  </body>

</body>
</html>

login/templates/login.html
<!DOCTYPE html>
<html lang="it">
<head>
  <title>Autenticazione HAL</title>
  <title>HAL Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>


  <div class="d-flex aligns-items-center justify-content-center card  w-75 position-absolute top-50 start-50 translate-middle">
    <div class="card"" >
<div class="container mt-5" id="main">
  <h2 class="text-center">HAL LOGIN</h2>
  <form action="" method="POST">
      {% csrf_token %}
    <div class="mb-3 mt-3">
      <label for="Username">Username:</label>
      <input type="text" class="form-control" id="email" placeholder="Digita username " name="username">
    </div>
    <div class="mb-3">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="password" placeholder="Digita password" name="password">
    </div>

      {% if messages %}
        {%for messages in messages%}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{messages}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endfor%}
      {%endif%}

    <div class="mb-5">
    <button type="submit" class="btn btn-primary">Login</button>
    <label for="Register">Non sei registrato? <a href="{% url 'register_user' %}"> Registrati ora </a></label>
  </div>
</div>
</div>
</div>



</body>
</html>

login/templates/nav_bar.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<nav class="navbar navbar-expand-sm navbar-light sticky-top bg-light">
  <div class="container-fluid">

      <a class="navbar-brand" href="{% url 'home' %}">
        <span class="navbar-text text-left text-primary"> HAL   </span>
      </a>

         <span class="navbar-text text-center"> {{user.first_name}} {{user.last_name}}   </span>

         <div class="dropdown dropstart text-end">
           <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown">
            <img src="{% static '/blank-profile-picture.png' %}" style="width:40px;" class="rounded-pill float-right">
          </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"> Impostazioni Profilo </a></li>
                <li><a class="dropdown-item" name="logout" href="{% url 'logout_user' %}"> Logout </a> </li>
            </ul>
          </div>

  </div>
</nav>

login/templates/register.html
<!DOCTYPE html>
<html lang="it">
<head>
  <title>Registrazione HAL</title>
  <meta charset="utf-8">
  <title>HAL Register</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>


  <div class="d-flex aligns-items-center justify-content-center card  w-75 position-absolute top-50 start-50 translate-middle">
    <div class="card"" >
<div class="container mt-5" id="main">
  <h2 class="text-center">HAL REGISTRAZIONE</h2>
  <form action="{% url 'register_user' %}" method="POST">
      {% csrf_token %}

        <div class="col mb-3">
          <input type="text" class="form-control" placeholder="Nome" name="first_name">
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Cognome" name="last_name">
        </div>

    <div class="mb-3 mt-3">
      <input type="text" class="form-control" id="username" placeholder="Scegli il tuo username" name="username">
      <small id="tex" class="text-muted">
        Ricorda il tuo username per il login
      </small>
    </div>

    <div class="mb-3 mt-3">
      <input type="email" class="form-control" id="email" placeholder="Digita la tua email" name="email">
    </div>

    <div class="mb-3">
      <input type="password" class="form-control" id="password" placeholder="Digita password" name="password1" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="La password deve contenere almeno
      una lettere in maiuscolo una in miniuscolo e almeno 8 o più caratteri" required>
      <small>
        <ul>
            <li>La password non può essere simile alle altre informazioni personali. </li>
            <li>
              La password deve contenere almeno 8 caratteri.
            </li>
            <li> La password non deve essere una comune.</li>
            <li> La tua password non può essere interamente numerica.</li>
        </ul>
      </small>
    </div>


    <div class="mb-3">
      <input type="password" class="form-control" id="re-password" placeholder="Ripeti password" name="password2">
    </div>


      {% if form.errors %}
        {%for messages in messages%}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{messages}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endfor%}
      {%endif%}

    <div class="mb-5">
    <button type="submit" class="btn btn-primary">Registrati</button>
    <label for="Register">Hai già un account? <a href="{% url 'login_user' %}""> Login </a></label>
  </div>
</div>
</div>
</div>



</body>
</html>